"""
Latency Arbitrage Strategy Module.

Latency-based trading strategy implementation.
"""

from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple
from datetime import datetime

from features.builder import FeatureVector
from config.settings import settings
from config.assets import get_asset, get_correlated_assets, DEFAULT_TRADING_PAIRS


@dataclass
class LatencySignal:
    """Signal generated by latency strategy."""
    symbol: str
    primary_symbol: str
    secondary_symbol: str
    direction: str  # "long", "short"
    entry_price: float
    confidence: float
    stop_loss: float
    take_profit: float
    position_size: float
    correlation: float
    lag_seconds: float
    reason: str
    timestamp: datetime = None
    
    def __post_init__(self):
        if self.timestamp is None:
            self.timestamp = datetime.now()


class LatencyStrategy:
    """
    Latency arbitrage strategy.
    
    Trades on price divergence between correlated assets.
    When one asset moves, the other typically follows with a lag.
    
    Entry conditions:
    - Significant shipping event detected
    - Price divergence between correlated assets
    - Correlation above threshold
    
    Exit conditions:
    - Correlation reestablished
    - Price convergence
    - Time-based exit
    """
    
    def __init__(self):
        self.name = "latency"
        self.min_correlation = 0.6
        self.divergence_threshold = 0.02  # 2% divergence
        self.max_lag_seconds = 60.0
        self.correlation_history: Dict[str, List[float]] = {}
    
    def analyze(self, features: FeatureVector, 
               correlated_features: Dict[str, FeatureVector] = None) -> Optional[LatencySignal]:
        """Analyze features and generate signal."""
        # Check if this is a high-shipping-impact asset
        if features.shipping_impact < 1.0:
            return None
        
        # Get correlated assets
        correlated = get_correlated_assets(features.symbol)
        if not correlated:
            return None
        
        # Find divergence opportunities
        divergence = self._find_divergence(features, correlated_features or {})
        
        if divergence is None:
            return None
        
        primary, secondary, direction, lag = divergence
        
        # Calculate entry and exits
        entry_price = features.price
        divergence_size = abs(entry_price - secondary.price) / secondary.price
        
        if direction == "long":
            stop_loss = entry_price * (1 - settings.stop_loss_pct)
            take_profit = entry_price * (1 + settings.take_profit_pct)
        else:
            stop_loss = entry_price * (1 + settings.stop_loss_pct)
            take_profit = entry_price * (1 - settings.take_profit_pct)
        
        # Calculate confidence
        confidence = self._calculate_confidence(features, primary, secondary, direction)
        
        return LatencySignal(
            symbol=features.symbol,
            primary_symbol=primary.symbol if hasattr(primary, 'symbol') else features.symbol,
            secondary_symbol=secondary.symbol if hasattr(secondary, 'symbol') else "",
            direction=direction,
            entry_price=round(entry_price, 2),
            confidence=round(confidence, 3),
            stop_loss=round(stop_loss, 2),
            take_profit=round(take_profit, 2),
            position_size=min(settings.max_capital_per_trade, confidence * settings.max_capital_per_trade),
            correlation=primary.shipping_impact if hasattr(primary, 'shipping_impact') else 0.8,
            lag_seconds=lag,
            reason=self._generate_reason(features, primary, secondary, direction)
        )
    
    def _find_divergence(self, features: FeatureVector,
                        correlated_features: Dict[str, FeatureVector]) -> Optional[Tuple]:
        """Find price divergence between correlated assets."""
        divergences = []
        
        # Check against correlated assets
        for corr_symbol in features.symbol:
            corr_features = correlated_features.get(corr_symbol)
            if not corr_features:
                continue
            
            # Calculate price divergence
            primary_change = features.price_change_short
            secondary_change = corr_features.price_change_short
            
            divergence = primary_change - secondary_change
            
            # Check if significant divergence
            if abs(divergence) > self.divergence_threshold * 100:
                direction = "long" if divergence > 0 and primary_change > 0 else "short"
                
                divergences.append((
                    features,
                    corr_features,
                    direction,
                    30.0  # Estimated lag
                ))
        
        # Also check against shipping index movement
        if features.shipping_impact > 1.1:
            # Shipping impact is high - check for delayed reaction
            if features.price_change_short < 0.5 and features.event_severity > 0.4:
                # Stock hasn't reacted to shipping news yet
                divergences.append((
                    features,
                    None,  # Reference is "fair value"
                    "long",
                    45.0
                ))
        
        # Return best divergence
        if divergences:
            return max(divergences, key=lambda x: abs(
                x[0].price_change_short - (x[1].price_change_short if x[1] else 0)
            ))
        
        return None
    
    def _calculate_confidence(self, features: FeatureVector,
                             primary, secondary, direction: str) -> float:
        """Calculate signal confidence."""
        confidence = 0.4
        
        # Correlation strength
        if hasattr(primary, 'shipping_impact'):
            confidence += primary.shipping_impact * 0.2
        
        # Event severity
        if features.event_severity > 0.5:
            confidence += 0.2
        
        # Volume
        if features.volume_ratio > 1.2:
            confidence += 0.1
        
        # Sentiment alignment
        if features.shipping_sentiment > 0.3:
            confidence += 0.1
        
        return min(1.0, confidence)
    
    def _generate_reason(self, features: FeatureVector,
                        primary, secondary, direction: str) -> str:
        """Generate human-readable reason."""
        parts = [f"Latency {direction} on {features.symbol}"]
        
        if hasattr(primary, 'symbol'):
            parts.append(f"vs {primary.symbol}")
        
        if features.event_severity > 0.4:
            parts.append(f"Event sev: {features.event_severity:.2f}")
        
        parts.append(f"Shipping impact: {features.shipping_impact:.2f}")
        
        return " | ".join(parts)
    
    def should_exit(self, features: FeatureVector, entry_price: float,
                   current_price: float, direction: str,
                   stop_loss: float, take_profit: float) -> Tuple[bool, str]:
        """
        Check if should exit position.
        
        Returns: (should_exit, reason)
        """
        # Check stop loss
        if direction == "long" and current_price <= stop_loss:
            return True, "stop_loss"
        elif direction == "short" and current_price >= stop_loss:
            return True, "stop_loss"
        
        # Check take profit
        if direction == "long" and current_price >= take_profit:
            return True, "take_profit"
        elif direction == "short" and current_price <= take_profit:
            return True, "take_profit"
        
        # Check convergence (when the lag is resolved)
        convergence_threshold = 0.005  # 0.5%
        price_diff = abs(current_price - entry_price) / entry_price
        if price_diff < convergence_threshold:
            return True, "convergence"
        
        return False, ""
    
    def update_correlation(self, symbol: str, correlation: float):
        """Update correlation history for a symbol pair."""
        if symbol not in self.correlation_history:
            self.correlation_history[symbol] = []
        
        self.correlation_history[symbol].append(correlation)
        
        # Keep last 100 observations
        if len(self.correlation_history[symbol]) > 100:
            self.correlation_history[symbol] = self.correlation_history[symbol][-100:]
    
    def get_average_correlation(self, symbol: str) -> float:
        """Get average correlation for a symbol."""
        history = self.correlation_history.get(symbol, [])
        if not history:
            return self.min_correlation
        return sum(history) / len(history)


# Singleton
_latency_strategy = None

def get_latency_strategy() -> LatencyStrategy:
    """Get latency strategy instance."""
    global _latency_strategy
    if _latency_strategy is None:
        _latency_strategy = LatencyStrategy()
    return _latency_strategy
