"""
Mean Reversion Strategy Module.

Mean reversion trading strategy implementation.
"""

from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple
from datetime import datetime

from features.builder import FeatureVector
from config.settings import settings


@dataclass
class MeanReversionSignal:
    """Signal generated by mean reversion strategy."""
    symbol: str
    direction: str  # "long", "short"
    entry_price: float
    confidence: float
    stop_loss: float
    take_profit: float
    position_size: float
    mean_price: float
    z_score: float
    reason: str
    timestamp: datetime = None
    
    def __post_init__(self):
        if self.timestamp is None:
            self.timestamp = datetime.now()


class MeanReversionStrategy:
    """
    Mean reversion trading strategy.
    
    Trades against sharp overreactions in price.
    
    Entry conditions:
    - RSI at extreme (oversold < 35 or overbought > 65)
    - Price at Bollinger Band extreme
    - Sharp move with volume
    
    Exit conditions:
    - RSI returned to neutral (50)
    - Price returned to mean
    - Stop loss hit
    """
    
    def __init__(self):
        self.name = "mean_reversion"
        self.rsi_oversold = 35
        self.rsi_overbought = 65
        self.rsi_neutral = 50
        self.bollinger_extreme = 0.2  # Position at band (0=lower, 1=upper)
        self.z_score_threshold = 1.5
        self.reversion_target = 0.5  # Target Bollinger position
    
    def analyze(self, features: FeatureVector) -> Optional[MeanReversionSignal]:
        """Analyze features and generate signal."""
        # Check entry conditions
        conditions_met, direction = self._check_entry_conditions(features)
        
        if not conditions_met:
            return None
        
        # Calculate mean (Bollinger middle band)
        mean_price = features.raw_indicators.bollinger_middle if features.raw_indicators else features.price
        
        # Calculate z-score
        z_score = self._calculate_z_score(features)
        
        # Calculate entry and exits
        entry_price = features.price
        atr = features.raw_indicators.atr if features.raw_indicators else features.price * 0.01
        
        # Tighter stops for mean reversion
        if direction == "long":
            stop_loss = entry_price * (1 - settings.stop_loss_pct * 0.8)
            take_profit = mean_price  # Target mean
        else:
            stop_loss = entry_price * (1 + settings.stop_loss_pct * 0.8)
            take_profit = mean_price
        
        # Calculate confidence
        confidence = self._calculate_confidence(features, direction, z_score)
        
        # Position size
        position_size = min(
            settings.max_capital_per_trade,
            self._calculate_position_size(features, z_score)
        )
        
        return MeanReversionSignal(
            symbol=features.symbol,
            direction=direction,
            entry_price=round(entry_price, 2),
            confidence=round(confidence, 3),
            stop_loss=round(stop_loss, 2),
            take_profit=round(take_profit, 2),
            position_size=position_size,
            mean_price=round(mean_price, 2),
            z_score=round(z_score, 2),
            reason=self._generate_reason(features, direction, z_score)
        )
    
    def _check_entry_conditions(self, features: FeatureVector) -> Tuple[bool, str]:
        """Check if entry conditions are met."""
        # Oversold conditions (expect bounce)
        oversold_conditions = [
            features.rsi <= self.rsi_oversold,
            features.bollinger_position <= self.bollinger_extreme,
            features.volume_ratio > 1.2,
            features.price_change_short < -1.5  # Sharp drop
        ]
        
        # Overbought conditions (expect pullback)
        overbought_conditions = [
            features.rsi >= self.rsi_overbought,
            features.bollinger_position >= (1 - self.bollinger_extreme),
            features.volume_ratio > 1.2,
            features.price_change_short > 1.5  # Sharp rise
        ]
        
        oversold_score = sum(oversold_conditions)
        overbought_score = sum(overbought_conditions)
        
        # Need at least 3 conditions for high confidence
        if oversold_score >= 3:
            return True, "long"
        elif overbought_score >= 3:
            return True, "short"
        
        # Partial conditions - still valid but lower confidence
        if features.rsi <= 40 and features.bollinger_position <= 0.25:
            return True, "long"
        elif features.rsi >= 60 and features.bollinger_position >= 0.75:
            return True, "short"
        
        return False, "neutral"
    
    def _calculate_z_score(self, features: FeatureVector) -> float:
        """Calculate z-score of current price vs mean."""
        mean = features.raw_indicators.bollinger_middle if features.raw_indicators else features.price
        std = features.raw_indicators.std_dev if features.raw_indicators else features.price * 0.02
        
        if std == 0:
            return 0.0
        
        z_score = (features.price - mean) / std
        return z_score
    
    def _calculate_confidence(self, features: FeatureVector, 
                             direction: str, z_score: float) -> float:
        """Calculate signal confidence."""
        confidence = 0.5
        
        # RSI extremity
        if direction == "long":
            if features.rsi < 30:
                confidence += 0.2
            elif features.rsi < 35:
                confidence += 0.1
        else:
            if features.rsi > 70:
                confidence += 0.2
            elif features.rsi > 65:
                confidence += 0.1
        
        # Bollinger extremity
        if direction == "long" and features.bollinger_position < 0.15:
            confidence += 0.15
        elif direction == "short" and features.bollinger_position > 0.85:
            confidence += 0.15
        
        # Z-score
        if abs(z_score) > 2.0:
            confidence += 0.1
        
        # Volume confirmation
        if features.volume_ratio > 1.5:
            confidence += 0.05
        
        return min(1.0, confidence)
    
    def _calculate_position_size(self, features: FeatureVector, 
                                  z_score: float) -> float:
        """Calculate position size based on z-score."""
        # Higher z-score = better entry = larger position
        base_size = settings.max_capital_per_trade * 0.8
        
        # Adjust by z-score magnitude
        z_factor = min(1.0, abs(z_score) / 2.0)
        size = base_size * (0.5 + z_factor * 0.5)
        
        return size
    
    def _generate_reason(self, features: FeatureVector, 
                        direction: str, z_score: float) -> str:
        """Generate human-readable reason."""
        parts = [f"Mean reversion {direction} on {features.symbol}"]
        
        if direction == "long":
            parts.append(f"Oversold RSI: {features.rsi:.1f}")
            parts.append(f"At lower BB")
        else:
            parts.append(f"Overbought RSI: {features.rsi:.1f}")
            parts.append(f"At upper BB")
        
        parts.append(f"Z-score: {z_score:.2f}")
        
        return " | ".join(parts)
    
    def should_exit(self, features: FeatureVector, entry_price: float,
                   current_price: float, direction: str,
                   stop_loss: float, take_profit: float) -> Tuple[bool, str]:
        """
        Check if should exit position.
        
        Returns: (should_exit, reason)
        """
        # Check stop loss
        if direction == "long" and current_price <= stop_loss:
            return True, "stop_loss"
        elif direction == "short" and current_price >= stop_loss:
            return True, "stop_loss"
        
        # Check mean reversion complete (RSI near neutral)
        if direction == "long" and features.rsi >= self.rsi_neutral + 10:
            return True, "mean_reverted"
        elif direction == "short" and features.rsi <= self.rsi_neutral - 10:
            return True, "mean_reverted"
        
        # Check Bollinger position returned to center
        if abs(features.bollinger_position - self.reversion_target) < 0.15:
            return True, "bollinger_reverted"
        
        # Check take profit (reached mean)
        mean_price = features.raw_indicators.bollinger_middle if features.raw_indicators else take_profit
        if direction == "long" and current_price >= mean_price:
            return True, "take_profit"
        elif direction == "short" and current_price <= mean_price:
            return True, "take_profit"
        
        # Time-based exit (mean reversion trades should be shorter)
        # This would be checked externally
        
        return False, ""
    
    def calculate_expected_return(self, features: FeatureVector, 
                                   entry_price: float) -> float:
        """Calculate expected return if mean reversion completes."""
        mean_price = features.raw_indicators.bollinger_middle if features.raw_indicators else entry_price
        
        # Return to mean
        return_pct = (mean_price - entry_price) / entry_price
        
        return round(return_pct * 100, 2)


# Singleton
_mean_reversion_strategy = None

def get_mean_reversion_strategy() -> MeanReversionStrategy:
    """Get mean reversion strategy instance."""
    global _mean_reversion_strategy
    if _mean_reversion_strategy is None:
        _mean_reversion_strategy = MeanReversionStrategy()
    return _mean_reversion_strategy
