"""
Momentum Strategy Module.

Momentum-based trading strategy implementation.
"""

from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple
from datetime import datetime

from features.builder import FeatureVector
from config.settings import settings


@dataclass
class MomentumSignal:
    """Signal generated by momentum strategy."""
    symbol: str
    direction: str  # "long", "short"
    entry_price: float
    confidence: float
    stop_loss: float
    take_profit: float
    position_size: float  # As fraction of capital
    reason: str
    timestamp: datetime = None
    
    def __post_init__(self):
        if self.timestamp is None:
            self.timestamp = datetime.now()


class MomentumStrategy:
    """
    Momentum trading strategy.
    
    Entry conditions:
    - Price breakout above recent high
    - Volume confirmation (above average)
    - RSI in favor of direction
    
    Exit conditions:
    - Stop loss at entry - ATR * factor
    - Take profit at entry + ATR * factor
    - RSI reversal
    - Volume collapse
    """
    
    def __init__(self):
        self.name = "momentum"
        self.breakout_threshold = 0.02  # 2% breakout
        self.volume_confirmation = 1.3  # 1.3x average volume
        self.atr_multiplier = 2.0
        self.rsi_entry_long = 55
        self.rsi_entry_short = 45
    
    def analyze(self, features: FeatureVector) -> Optional[MomentumSignal]:
        """Analyze features and generate signal."""
        # Check entry conditions
        conditions_met, direction = self._check_entry_conditions(features)
        
        if not conditions_met:
            return None
        
        # Calculate entry and exit prices
        entry_price = features.price
        atr = features.raw_indicators.atr if features.raw_indicators else features.price * 0.01
        
        if direction == "long":
            stop_loss = entry_price - (atr * self.atr_multiplier)
            take_profit = entry_price + (atr * self.atr_multiplier * 1.5)
        else:
            stop_loss = entry_price + (atr * self.atr_multiplier)
            take_profit = entry_price - (atr * self.atr_multiplier * 1.5)
        
        # Calculate confidence
        confidence = self._calculate_confidence(features, direction)
        
        # Calculate position size (max 1% of capital)
        position_size = min(
            settings.max_capital_per_trade,
            self._calculate_position_size(features)
        )
        
        return MomentumSignal(
            symbol=features.symbol,
            direction=direction,
            entry_price=round(entry_price, 2),
            confidence=round(confidence, 3),
            stop_loss=round(stop_loss, 2),
            take_profit=round(take_profit, 2),
            position_size=position_size,
            reason=self._generate_reason(features, direction)
        )
    
    def _check_entry_conditions(self, features: FeatureVector) -> Tuple[bool, str]:
        """Check if entry conditions are met."""
        # Long entry conditions
        long_conditions = [
            features.price_change_short > self.breakout_threshold * 100,
            features.volume_ratio > self.volume_confirmation,
            features.rsi > self.rsi_entry_long,
            features.momentum_score > 0.6
        ]
        
        # Short entry conditions
        short_conditions = [
            features.price_change_short < -self.breakout_threshold * 100,
            features.volume_ratio > self.volume_confirmation,
            features.rsi < self.rsi_entry_short,
            features.momentum_score < 0.4
        ]
        
        long_score = sum(long_conditions)
        short_score = sum(short_conditions)
        
        # Need at least 3 conditions
        if long_score >= 3:
            return True, "long"
        elif short_score >= 3:
            return True, "short"
        
        return False, "neutral"
    
    def _calculate_confidence(self, features: FeatureVector, direction: str) -> float:
        """Calculate signal confidence."""
        confidence = 0.5
        
        # Volume confirmation boost
        if features.volume_ratio > 1.5:
            confidence += 0.15
        elif features.volume_ratio > 1.3:
            confidence += 0.1
        
        # RSI strength boost
        if direction == "long" and features.rsi > 60:
            confidence += 0.15
        elif direction == "short" and features.rsi < 40:
            confidence += 0.15
        
        # Momentum score
        if direction == "long" and features.momentum_score > 0.7:
            confidence += 0.1
        elif direction == "short" and features.momentum_score < 0.3:
            confidence += 0.1
        
        # Event support
        if features.event_severity > 0.5:
            confidence += 0.1
        
        return min(1.0, confidence)
    
    def _calculate_position_size(self, features: FeatureVector) -> float:
        """Calculate position size based on confidence and volatility."""
        # Higher confidence = larger position
        base_size = features.momentum_score * settings.max_capital_per_trade
        
        # Reduce for high volatility
        if features.raw_indicators and features.raw_indicators.std_dev:
            volatility_penalty = min(0.5, features.raw_indicators.std_dev / features.price)
            base_size *= (1 - volatility_penalty)
        
        return base_size
    
    def _generate_reason(self, features: FeatureVector, direction: str) -> str:
        """Generate human-readable reason for signal."""
        parts = [f"Momentum {direction} signal"]
        
        if features.volume_ratio > 1.3:
            parts.append(f"Volume {features.volume_ratio:.1f}x")
        
        if direction == "long" and features.rsi > 55:
            parts.append(f"RSI {features.rsi:.1f}")
        elif direction == "short" and features.rsi < 45:
            parts.append(f"RSI {features.rsi:.1f}")
        
        if features.price_change_short > 1:
            parts.append(f"+{features.price_change_short:.1f}%")
        elif features.price_change_short < -1:
            parts.append(f"{features.price_change_short:.1f}%")
        
        return " | ".join(parts)
    
    def should_exit(self, features: FeatureVector, entry_price: float, 
                   current_price: float, direction: str,
                   stop_loss: float, take_profit: float) -> Tuple[bool, str]:
        """
        Check if should exit position.
        
        Returns: (should_exit, reason)
        """
        # Check stop loss
        if direction == "long" and current_price <= stop_loss:
            return True, "stop_loss"
        elif direction == "short" and current_price >= stop_loss:
            return True, "stop_loss"
        
        # Check take profit
        if direction == "long" and current_price >= take_profit:
            return True, "take_profit"
        elif direction == "short" and current_price <= take_profit:
            return True, "take_profit"
        
        # Check RSI reversal
        if direction == "long" and features.rsi < 40:
            return True, "rsi_reversal"
        elif direction == "short" and features.rsi > 60:
            return True, "rsi_reversal"
        
        # Check momentum collapse
        if features.volume_ratio < 0.5:
            return True, "volume_collapse"
        
        return False, ""


# Singleton
_momentum_strategy = None

def get_momentum_strategy() -> MomentumStrategy:
    """Get momentum strategy instance."""
    global _momentum_strategy
    if _momentum_strategy is None:
        _momentum_strategy = MomentumStrategy()
    return _momentum_strategy
